### ISSUE TITLE
path to page name is different in screen shot and info on page

### ISSUE THREAD

**Issue by sayabannatole** [AdobeDocs/experience-cloud.en#3]
Issue in help/website-implementation/launch-data-elements-rules.md

Hi,

The Page Name defined to have java script variable when defining the data element in Launch is given as "digitalData.page.pageInfo.pageName" in steps but the screen shot shows the value as "digitalData.pageName". Can you please confirm which one is the correct value to be followed here?

Thanks,
Sayabanna

**Comment by dwright-adobe** [comment]
good catch Sayabanna, "digitalData.page.pageInfo.pageName" is the correct value. I need to update the screenshot

**Comment by dwright-adobe** [comment]
Fixed: https://docs.adobe.com/content/help/en/experience-cloud/implementing-in-websites-with-launch/configure-launch/launch-data-elements-rules.html
